bigquery:
  project_id: project_id

slack:
  channel: "#notify"

tables:
  - dataset_id: dataset_id1
    table_id: analytics_events
    date_suffix: "two_days_ago" # "yesterday" # or first_day_of_month or first_day_of_year
    check_frequency: 24  # hours
    check_time: "12:00" # 24-hour format
